# ###############################################
# DEFAULT PROFILE (applies to all profiles)
# ###############################################
server:
  port: 8081

spring:
  application:
    name: cartcraft

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Remove the main 'active' profile from here, as it's set in IntelliJ

# Use three hyphens to start a new, profile-specific configuration
---

# ###############################################
# DEVELOPMENT PROFILE
# ###############################################
spring:
  config:
    activate:
      on-profile: "dev" # This block is now only active for the 'dev' profile
  datasource:
    url: jdbc:postgresql://localhost:5433/cartcraftdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    com.cartcraft: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE