server:
  port: 8081

spring:
  application:
    name: cartcraft
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/cartcraftdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    com.cartcraft: DEBUG
    org.hibernate.SQL: DEBUG                # Show SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show query parameter bindings

